# Remote state, configured at init time rather than hardcoded -- the bucket
# name is generated by the bootstrap and is account-specific, so it does not
# belong in version control.
#
#   terraform init -backend-config=backend.hcl
#
# `terraform init -backend=false` still works for validation, which is what
# CI and `make tf-validate` use, so neither needs the bucket to exist.

terraform {
  backend "s3" {}
}
